language: python


matrix:
    include:
        - os: linux
          python: 2.6
        - os: linux
          python: 2.7
        - os: linux
          python: 3.3
        - os: linux
          python: 3.4
        - os: linux
          python: 3.5

        - os: osx
          python: 2.6
        - os: osx
          python: 2.7
        - os: osx
          python: 3.3
        - os: osx
          python: 3.4
        - os: osx
          python: 3.5

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install gfortran; fi

install:
    - pip install -r requirements.txt
    - python setup.py install --force-tempo2-install

script:
    - cd ../
    - python -c "print(open('libstempo/libstempo/__init__.py', 'r').read())"
    - python -c "import libstempo"
    - python -c "import libstempo.toasim"
