language: python


matrix:
    include:
        # All the versions of Python.
        - python: 2.6
        - python: 2.7
        - python: 3.3
        - python: 3.4
        - python: 3.5

before_install:
    - git clone https://bitbucket.org/psrsoft/tempo2.git
    - cd tempo2
    - ./bootstrap
    - mkdir -p $HOME/.local/tempo2
    - export TEMPO2=$HOME/.local/tempo2
    - cp -r T2runtime/* $TEMPO2
    - ./configure --prefix=$TEMPO2
    - make && make install
    - cd ../

install:
    - pip install -r requirements.txt
    - python setup.py install --with-tempo2=$TEMPO2

script:
    - which python
