name: Release - Conda

on:
  release: 
    types:
      - published

jobs:
  build_and_package:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Install miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: false
          activate-environment: "build-libstempo"
          channels: jellis1895

      - name: Setup conda env
        run: |
          conda install -c defaults anaconda-client conda-build

      - name: Build conda packages
        run: |
          conda info
          conda list
          conda build conda -c conda-forge -c defaults -m conda/conda_build_config.yaml
      - name: Upload to Anaconda
        run: |
          anaconda login --username ${{ secrets.ANACONDA_USERNAME }} --password ${{ secrets.ANACONDA_PASSWORD }}
          anaconda upload `conda-build conda --output`